// Array of Marvel Characters
const marvelCharacters = [
    {
      name: "Iron Man",
      realName: "Tony Stark",
      height: 6.2,
      weight: 200,
      power: 100,
      intelligence: 100,
      speed: 100,
      strength: 100,
      agility: 100,
      durability: 100,
      energyProjection: 100,
      fightingSkills: 100,
    },
    {
      name: "Captain America",
      realName: "Steve Rogers",
      height: 6.2,
      weight: 200,
      power: 100,
      intelligence: 100,
      speed: 100,
      strength: 100,
      agility: 100,
      durability: 100,
      energyProjection: 100,
      fightingSkills: 100,
    },
    {
      name: "Thor",
      realName: "Thor Odinson",
      height: 6.2,
      weight: 200,
      power: 100,
      intelligence: 100,
      speed: 100,
      strength: 100,
      agility: 100,
      durability: 100,
      energyProjection: 100,
      fightingSkills: 100,
    },
    {
      name: "Hulk",
      realName: "Bruce Banner",
      height: 6.2,
      weight: 200,
      power: 100,
      intelligence: 100,
      speed: 100,
      strength: 100,
      agility: 100,
      durability: 100,
      energyProjection: 100,
      fightingSkills: 100,
    },
    {
      name: "Black Widow",
      realName: "Natasha Romanoff",
      height: 5.11,
      weight: 125,
      power: 100,
      intelligence: 100,
      speed: 100,
      strength: 100,
      agility: 100,
      durability: 100,
      energyProjection: 100,
      fightingSkills: 100,
    },
    {
      name: "Hawkeye",
      realName: "Clint Barton",
      height: 5.11,
      weight: 125,
      power: 100,
      intelligence: 100,
      speed: 100,
      strength: 100,
      agility: 100,
      durability: 100,
      energyProjection: 100,
      fightingSkills: 100,
    },
    {
      name: "Black Panther",
      realName: "T'Challa",
      height: 6.0,
      weight: 200,
      power: 100,
      intelligence: 100,
      speed: 100,
      strength: 100,
      agility: 100,
      durability: 100,
      energyProjection: 100,
      fightingSkills: 100,
    },
    {
      name: "Wolverine",
      realName: "James Howlett",
      height: 5.3,
      weight: 200,
      power: 100,
      intelligence: 100,
      speed: 100,
      strength: 100,
      agility: 100,
      durability: 100,
      energyProjection: 100,
      fightingSkills: 100,
    },
    {
      name: "Captain Marvel",
      realName: "Carol Danvers",
      height: 6.2,
      weight: 200,
      power: 100,
      intelligence: 100,
      speed: 100,
      strength: 100,
      agility: 100,
      durability: 100,
      energyProjection: 100,
      fightingSkills: 100,
    },
    {
      name: "Doctor Strange",
      realName: "Stephen Strange",
      height: 6.2,
      weight: 200,
      power: 100,
      intelligence: 100,
      speed: 100,
      strength: 100,
      agility: 100,
      durability: 100,
      energyProjection: 100,
      fightingSkills: 100,
    },
  ];
  
  const dcCharacters = [
    {
      name: "Batman",
      realName: "Bruce Wayne",
      height: 6.2,
      weight: 200,
      power: 100,
      intelligence: 100,
      speed: 100,
      strength: 100,
      agility: 100,
      durability: 100,
      energyProjection: 100,
      fightingSkills: 100,
    },
    {
      name: "Superman",
      realName: "Clark Kent",
      height: 6.2,
      weight: 200,
      power: 100,
      intelligence: 100,
      speed: 100,
      strength: 100,
      agility: 100,
      durability: 100,
      energyProjection: 100,
      fightingSkills: 100,
    },
    {
      name: "Aquaman",
      realName: "Arthur Curry",
      height: 6.2,
      weight: 200,
      power: 100,
      intelligence: 100,
      speed: 100,
      strength: 100,
      agility: 100,
      durability: 100,
      energyProjection: 100,
      fightingSkills: 100,
    }
  ];
  
  // Array of strings with the names of the characters
  const marvelCharactersNames = [
    'Iron Man',
    'Captain America',
    'Thor',
    'Hulk',
    'Black Widow',
    'Hawkeye',
    'Black Panther',
    'Wolverine',
    'Captain Marvel',
    'Doctor Strange'
  ];
  
  // Array of strings with the real names of the characters
  const marvelCharactersRealNames = [
    'Tony Stark',
    'Steve Rogers',
    'Thor Odinson',
    'Bruce Banner',
    'Natasha Romanoff',
    'Clint Barton',
    'T\'Challa',
    'James Howlett',
    'Carol Danvers',
    'Stephen Strange'
  ];
  const marvel = marvelCharactersRealNames.map(element => {
    return element.toUpperCase();
});
console.log(marvel);

var resultado = marvelCharacters.filter(tipo => tipo.height == 6);    
// resultado por filtro
console.log(resultado);